---
pipeline:
  build_image:
    image: docker:17.09.0-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t docker-filebeat-jenkins:$${DRONE_COMMIT_SHA} .
    when:
      event: [push, tag]

  image_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_filebeat_bot" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag docker-filebeat-jenkins:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/docker-filebeat-jenkins:$${DRONE_COMMIT_SHA}
      - docker tag docker-filebeat-jenkins:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/docker-filebeat-jenkins:latest
      - docker push quay.io/ukhomeofficedigital/docker-filebeat-jenkins:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/docker-filebeat-jenkins:latest
    when:
      event: push
      branch: master

  tag_to_quay:
    image: docker:17.09.0-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_filebeat_bot" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag docker-filebeat-jenkins:$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/docker-filebeat-jenkins:$${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/docker-filebeat-jenkins:$${DRONE_TAG}
    when:
      event: tag
